export const ACTOR_DETAILS_REQUEST = "ACTOR_DETAILS_REQUEST";
export const ACTOR_DETAILS_SUCCESS = "ACTOR_DETAILS_SUCCESS";
export const ACTOR_DETAILS_FAILED = "ACTOR_DETAILS_FAILED";

export const GET_TOKEN = "GET_TOKEN";
export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILED = "USER_INFO_FAILED";
export const DELETE_USER = "DELETE_USER";

export const SET_SESSION_ID = "SET_SESSION_ID";
export const SESSION_DELETE_SUCCESS = "SESSION_DELETE_SUCCESS";
export const SESSION_DELETE_FAILED = "SESSION_DELETE_FAILED";

export const KEYWORD_SEARCH_REQUEST = "KEYWORD_SEARCH_REQUEST";
export const KEYWORD_SEARCH_SUCCESS = "KEYWORD_SEARCH_SUCCESS";
export const KEYWORD_SEARCH_FAILED = "KEYWORD_SEARCH_FAILED";

export const GENRES_LIST_REQUEST = "GENRES_LIST_REQUEST";
export const GENRES_LIST_SUCCESS = "GENRES_LIST_SUCCESS";
export const GENRES_LIST_FAILED = "GENRES_LIST_FAILED";

export const MOVIE_CATEGORY_REQUEST = "MOVIE_CATEGORY_REQUEST";
export const MOVIE_CATEGORY_SUCCESS = "MOVIE_CATEGORY_SUCCESS";
export const MOVIE_CATEGORY_FAILED = "MOVIE_CATEGORY_FAILED";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILED = "MOVIE_DETAILS_FAILED";

export const SIMILAR_MOVIES_REQUEST = "SIMILAR_MOVIES_REQUEST";
export const SIMILAR_MOVIES_SUCCESS = "SIMILAR_MOVIES_SUCCESS";
export const SIMILAR_MOVIES_FAILED = "SIMILAR_MOVIES_FAILED";

export const ACCOUNT_STATES_REQUEST = "ACCOUNT_STATES_REQUEST";
export const ACCOUNT_STATES_SUCCESS = "ACCOUNT_STATES_SUCCESS";
export const ACCOUNT_STATES_FAILED = "ACCOUNT_STATES_FAILED";

export const UPDATE_ACCOUNT_REQUEST = "UPDATE_ACCOUNT_REQUEST";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED";

export const RATE_MOVIE_REQUEST = "RATE_MOVIE_REQUEST";
export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_FAILED = "RATE_MOVIE_FAILED";

export const DELETE_RATING_REQUEST = "DELETE_RATING_REQUEST";
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS";
export const DELETE_RATING_FAILED = "DELETE_RATING_FAILED";

export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
